### ISSUE TITLE
nvidia drivers

### ISSUE THREAD

**Issue by mrsteve0924** [archcraft-os/archcraft-wayfire#4]
did you really get nvidia proprietary drivers to work with wayfire?  i've been trying for weeks on my own wayfire build and cant get it to work. did all the same steps you outlined here but keeps crashing and complaining about eglstreams.

i'm using archlinux too.  any suggestions?

**Comment by adi1090x** [comment]
Just updated the configs, try again.

**Comment by mrsteve0924** [comment]
configs you mean the dotfiles in wayfire.tar.gz?
